// Generated by tools/generate_execution_package_mql.py; do not edit.
#ifndef RP_EXECUTION_PACKAGE_CONTRACT_MQH
#define RP_EXECUTION_PACKAGE_CONTRACT_MQH
#define RP_PACKAGE_SCHEMA_VERSION "1.0"
#define RP_PACKAGE_PRODUCER "RP_AI_RUNTIME"
#define RP_PACKAGE_PRODUCER_VERSION "27.5"
#define RP_EXECUTOR_PACKAGE_MAX_AGE_SECONDS 5
#define RP_EXECUTION_PACKAGE_FIELD_COUNT 18
enum RPJsonFieldType { RP_JSON_STRING, RP_JSON_INTEGER, RP_JSON_NUMBER };
void RPInitializePackageContract(string &names[], RPJsonFieldType &types[])
{
   ArrayResize(names, RP_EXECUTION_PACKAGE_FIELD_COUNT);
   ArrayResize(types, RP_EXECUTION_PACKAGE_FIELD_COUNT);
   names[0]="execution_uuid"; types[0]=RP_JSON_STRING;
   names[1]="decision_uuid"; types[1]=RP_JSON_STRING;
   names[2]="market_sequence"; types[2]=RP_JSON_INTEGER;
   names[3]="heartbeat_unix"; types[3]=RP_JSON_INTEGER;
   names[4]="producer"; types[4]=RP_JSON_STRING;
   names[5]="producer_version"; types[5]=RP_JSON_STRING;
   names[6]="schema_version"; types[6]=RP_JSON_STRING;
   names[7]="source_uuid"; types[7]=RP_JSON_STRING;
   names[8]="symbol"; types[8]=RP_JSON_STRING;
   names[9]="direction"; types[9]=RP_JSON_STRING;
   names[10]="confidence"; types[10]=RP_JSON_NUMBER;
   names[11]="risk_profile"; types[11]=RP_JSON_STRING;
   names[12]="lot_size"; types[12]=RP_JSON_NUMBER;
   names[13]="entry"; types[13]=RP_JSON_NUMBER;
   names[14]="sl"; types[14]=RP_JSON_NUMBER;
   names[15]="tp"; types[15]=RP_JSON_NUMBER;
   names[16]="management_profile"; types[16]=RP_JSON_STRING;
   names[17]="execution_timestamp"; types[17]=RP_JSON_STRING;
}
#endif
