from typing import Final
EVENT_TYPES: Final[frozenset[str]] = frozenset({
    "DECISION_OBSERVED", "ENTRY_REQUEST_OBSERVED", "ORDER_FILL_OBSERVED",
    "POSITION_UPDATE_OBSERVED", "EXIT_REQUEST_OBSERVED", "TRADE_CLOSED",
    "SNAPSHOT_CREATED", "SNAPSHOT_REJECTED", "DAILY_REVIEW_CREATED",
})
