"""Generate the MT5 package contract from the authoritative Python contract."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from execution_package_contract import (  # noqa: E402
    EXECUTION_PACKAGE_FIELDS,
    EXECUTION_PACKAGE_MQL_TYPES,
    EXECUTION_PACKAGE_SCHEMA_VERSION,
    EXECUTOR_PACKAGE_MAXIMUM_AGE_SECONDS,
)
from runtime.decision_publication import DECISION_PRODUCER, RUNTIME_VERSION  # noqa: E402

assert len(EXECUTION_PACKAGE_FIELDS) == len(EXUTION_TYPES := EXECUTION_PACKAGE_MQL_TYPES) == 18
lines = [
    "// Generated by tools/generate_execution_package_mql.py; do not edit.",
    "#ifndef RP_EXECUTION_PACKAGE_CONTRACT_MQH",
    "#define RP_EXECUTION_PACKAGE_CONTRACT_MQH",
    f'#define RP_PACKAGE_SCHEMA_VERSION "{EXECUTION_PACKAGE_SCHEMA_VERSION}"',
    f'#define RP_PACKAGE_PRODUCER "{DECISION_PRODUCER}"',
    f'#define RP_PACKAGE_PRODUCER_VERSION "{RUNTIME_VERSION}"',
    f"#define RP_EXECUTOR_PACKAGE_MAX_AGE_SECONDS {EXECUTOR_PACKAGE_MAXIMUM_AGE_SECONDS}",
    "#define RP_EXECUTION_PACKAGE_FIELD_COUNT 18",
    "enum RPJsonFieldType { RP_JSON_STRING, RP_JSON_INTEGER, RP_JSON_NUMBER };",
    "void RPInitializePackageContract(string &names[], RPJsonFieldType &types[])",
    "{",
    "   ArrayResize(names, RP_EXECUTION_PACKAGE_FIELD_COUNT);",
    "   ArrayResize(types, RP_EXECUTION_PACKAGE_FIELD_COUNT);",
]
for i, (name, kind) in enumerate(zip(EXECUTION_PACKAGE_FIELDS, EXUTION_TYPES)):
    lines.append(f'   names[{i}]="{name}"; types[{i}]=RP_JSON_{kind};')
lines += ["}", "#endif", ""]
(ROOT / "mt5/canonical/RP_ExecutionPackageContract.mqh").write_text("\n".join(lines), encoding="utf-8")
